# Generated by Django 4.0.5 on 2022-06-16 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='addres',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='clinicname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='1.png', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.CharField(blank=True, choices=[('mbbs', 'Mbbs'), ('md', 'Md'), ('ms', 'Ms'), ('bhms', 'Bhms'), ('bams', 'Bams'), ('bpt', 'Bpt')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('timeslot', models.CharField(choices=[('09:00 am To 10:00 am', '09:00 am To 10:00 am'), ('10:00 am To 11:00 am', '10:00 am TO 11:00 am'), ('11:00 am To 12:00 pm', '11:00 am To 12:00 pm'), ('12:00 pm To 01:00 pm', '12:00 pm To 01:00 pm'), ('02:00 pm To 03:00 pm', '02:00 pm To 03:00 pm'), ('03:00 pm To 04:00 pm', '03:00 pm To 04:00 pm'), ('04:00 pm To 05:00 pm', '04:00 pm To 05:00 pm')], max_length=50)),
                ('avalible_slot', models.IntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('absent', 'Absent'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('description', models.TextField(default=None)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.slot')),
            ],
        ),
    ]
